name: go-linter
on: [pull_request]
jobs:
  golang-lint:
    name: golang-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: api
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: "--config=../.github/golangci.yml"
          version: v1.45.0
          skip-pkg-cache: true
          skip-build-cache: true
